version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy:contrib-v1.33.2
    container_name: envoy-gateway
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../../dist/go-envoy-oauth.so:/app/go-envoy-oauth.so
    environment:
      - CLIENT_SECRET=${CLIENT_SECRET}
      - LOG_LEVEL=TRACE
      - COOKIE_CONFIG=HTTPOnly; SameSite=Lax
    ports:
      - "8081:8080"
      - "127.0.0.1:9901:9901"
    networks:
      - envoy-network

networks:
  envoy-network:
    driver: bridge
