version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy:contrib-v1.35.2
    container_name: envoy-gateway
    volumes:
      # - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../../dist/envoy-xds.yaml:/etc/envoy/envoy.yaml
      - ../../dist/go-envoy-oauth.so:/app/go-envoy-oauth.so
      - ./standalone.sh:/app/standalone.sh
      - ./gateway-auth.yaml:/app/gateway-auth.yaml
      - ./envoy.yaml:/app/gateway-base.yaml
      - ../../dist/xds-server:/app/xds-server
    environment:
      - OAUTH_CLIENTSECRET=${CLIENT_SECRET}
      - OAUTH_CLIENTID=${CLIENT_ID}
      - OAUTH_ISSUERURL=${ISSUER_URL}
      - OAUTH_ENABLE_API_KEY=true
      - LOG_LEVEL=TRACE
      - COOKIE_CONFIG=HTTPOnly; SameSite=Lax
    ports:
      - "8081:8080"
      - "127.0.0.1:9901:9901"
    command: /app/standalone.sh
    networks:
      - envoy-network

networks:
  envoy-network:
    driver: bridge
