version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command: start-dev
    networks:
      - envoy-network

  envoy:
    image: go-envoy-oauth:latest
    container_name: envoy-gateway
    volumes:
      - ./gateway-auth.yaml:/app/gateway-auth.yaml
    environment:
      - OAUTH_CLIENTSECRET=${CLIENT_SECRET}
      - OAUTH_CLIENTID=${CLIENT_ID}
      - OAUTH_ISSUERURL=${ISSUER_URL}
      - OAUTH_ENABLE_API_KEY=true
      - LOG_LEVEL=TRACE
      - COOKIE_CONFIG=HTTPOnly; SameSite=Lax
    ports:
      - "8081:8080"
      - "127.0.0.1:9901:9901"
    command: /app/standalone.sh
    networks:
      - envoy-network

networks:
  envoy-network:
    driver: bridge
