volumes:
  keycloak_data:
    driver: local
  shorts_data:
    driver: local

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      # KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      # KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # KC_PROXY_HEADERS: xforwarded
    command: start-dev
    networks:
      - envoy-network

  http-echo:
    image: jmalloc/echo-server
    container_name: http-echo
    networks:
      - envoy-network

  pk-shorts:
    image: ghcr.io/rashpile/pk-shorts
    container_name: shorts
    volumes:
      - shorts_data:/app/data
    networks:
      - envoy-network

  envoy:
    image: go-envoy-oauth:latest
    container_name: envoy-gateway
    volumes:
      - ./gateway-auth.yaml:/app/gateway-auth.yaml
    environment:
      - OAUTH_CLIENTSECRET=${CLIENT_SECRET}
      - OAUTH_CLIENTID=${CLIENT_ID}
      - OAUTH_ISSUERURL=${ISSUER_URL}
      - OAUTH_ENABLE_API_KEY=true
      - LOG_LEVEL=INFO
      - ACCESS_LOG=plain
    ports:
      - "8081:8081"
      - "127.0.0.1:9901:9901"
    networks:
      - envoy-network

networks:
  envoy-network:
    driver: bridge
